### ISSUE TITLE
August 29th, 2015 - NodeSchool Mentors

### ISSUE THREAD

**Issue by brianpmarks** [nodeschool/raleigh-durham#2]
We'll need up to 5 mentors to volunteer for our first NodeSchool event on Saturday, August 29th, 2015 from about 8:30am until 12:30pm. This event will be held in Durham at American Underground on Main Street.

If you have experience with node.js and would like to volunteer your expertise and time please add a comment with your name to this issue. Please also be prepared to help with installation of node.js, likely on several platforms, and familiarize yourself with the [NodeSchool Core Workshoppers](http://nodeschool.io/index.html#workshopper-list).

Thanks!

**Comment by pmuellr** [comment]
I should be able to help out.  Pencilled it into my calendar.

**Comment by Rleahy22** [comment]
Hi, I'm new to this meetup group, but I have experience with Node and would like to help out if needed.

**Comment by jbielick** [comment]
hey @brianpmarks, I'll be available. Still need the help?

**Comment by brianpmarks** [comment]
Thanks! Yes, I think the more that can help out the better. Right now we're at 60+ signed up.
