### ISSUE TITLE
May 21st, 2016 - Mentors for NodeSchool International Day

### ISSUE THREAD

**Issue by brianpmarks** [nodeschool/raleigh-durham#3]
We'll need up to 5 mentors to volunteer for our NodeSchool International Day event on Saturday, May 21st, 2016 from about 12:30pm until 5:30pm. This event will be held in Raleigh at HQ Raleigh.

If you have experience with node.js and would like to volunteer your expertise and time please add a comment with your name to this issue. Please also be prepared to help with installation of node.js, likely on several platforms, and familiarize yourself with the NodeSchool Core Workshoppers.

Thanks!

**Comment by jbielick** [comment]
I can be there!
